import { z } from 'zod';
export declare const FindingSeveritySchema: z.ZodEnum<["low", "medium", "high", "critical"]>;
export declare const FindingStatusSchema: z.ZodEnum<["open", "confirmed", "false_positive"]>;
export declare const FindingSchema: z.ZodObject<{
    id: z.ZodOptional<z.ZodString>;
    page_id: z.ZodOptional<z.ZodString>;
    run_id: z.ZodOptional<z.ZodString>;
    check_factor: z.ZodString;
    severity: z.ZodEnum<["low", "medium", "high", "critical"]>;
    title: z.ZodString;
    description: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    context_text: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    screenshot_url: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    status: z.ZodDefault<z.ZodEnum<["open", "confirmed", "false_positive"]>>;
    ai_generated: z.ZodDefault<z.ZodBoolean>;
    created_at: z.ZodOptional<z.ZodString>;
    updated_at: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    status: "open" | "confirmed" | "false_positive";
    title: string;
    severity: "critical" | "high" | "medium" | "low";
    check_factor: string;
    ai_generated: boolean;
    id?: string | undefined;
    description?: string | null | undefined;
    screenshot_url?: string | null | undefined;
    page_id?: string | undefined;
    run_id?: string | undefined;
    context_text?: string | null | undefined;
    created_at?: string | undefined;
    updated_at?: string | undefined;
}, {
    title: string;
    severity: "critical" | "high" | "medium" | "low";
    check_factor: string;
    id?: string | undefined;
    status?: "open" | "confirmed" | "false_positive" | undefined;
    description?: string | null | undefined;
    screenshot_url?: string | null | undefined;
    page_id?: string | undefined;
    run_id?: string | undefined;
    context_text?: string | null | undefined;
    ai_generated?: boolean | undefined;
    created_at?: string | undefined;
    updated_at?: string | undefined;
}>;
export type Finding = z.infer<typeof FindingSchema>;
export type FindingSeverity = z.infer<typeof FindingSeveritySchema>;
export type FindingStatus = z.infer<typeof FindingStatusSchema>;
//# sourceMappingURL=finding.schema.d.ts.map